//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VTOL.Resources.Languages {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Language {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Language() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("VTOL.Resources.Languages.Language", typeof(Language).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Location - &apos; .
        /// </summary>
        public static string Browse_Titanfall_Button_Click_TheLocation {
            get {
                return ResourceManager.GetString("Browse_Titanfall_Button_Click_TheLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Release Candidate Detected.
        /// </summary>
        public static string Check_For_New_Northstar_Install_ReleaseCandidateDetected {
            get {
                return ResourceManager.GetString("Check_For_New_Northstar_Install_ReleaseCandidateDetected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update Available Downloading And Installing Now!.
        /// </summary>
        public static string Check_For_New_Northstar_Install_UpdateAvailableDownloadingAndInstallingNow {
            get {
                return ResourceManager.GetString("Check_For_New_Northstar_Install_UpdateAvailableDownloadingAndInstallingNow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Directory Check Failed.
        /// </summary>
        public static string Check_Integrity_Of_NSINSTALL_DirectoryCheckFailed {
            get {
                return ResourceManager.GetString("Check_Integrity_Of_NSINSTALL_DirectoryCheckFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VTOL SYSTEMS FAILED TO FIND YOUR DOCUMENTS FOLDER.
        /// </summary>
        public static string MainWindow_MainWindow_VTOLSYSTEMSFAILEDTOFINDYOURDOCUMENTSFOLDER {
            get {
                return ResourceManager.GetString("MainWindow_MainWindow_VTOLSYSTEMSFAILEDTOFINDYOURDOCUMENTSFOLDER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ABOUT.
        /// </summary>
        public static string Page_About_ABOUT {
            get {
                return ResourceManager.GetString("Page_About_ABOUT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About VTOL and Documentation On its Use..
        /// </summary>
        public static string Page_About_AboutVTOLAndDocumentationOnItsUse {
            get {
                return ResourceManager.GetString("Page_About_AboutVTOLAndDocumentationOnItsUse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check For Update.
        /// </summary>
        public static string Page_About_CheckForUpdate {
            get {
                return ResourceManager.GetString("Page_About_CheckForUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configure Updates.
        /// </summary>
        public static string Page_About_ConfigureUpdates {
            get {
                return ResourceManager.GetString("Page_About_ConfigureUpdates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Defualt Textbox Text.
        /// </summary>
        public static string Page_About_DefualtTextboxText {
            get {
                return ResourceManager.GetString("Page_About_DefualtTextboxText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NORTHSTAR IS NOT INSTALLED AND AUTO INSTALL FAILED!.
        /// </summary>
        public static string Page_Home_Auto_Install__NORTHSTARISNOTINSTALLEDANDAUTOINSTALLFAILED {
            get {
                return ResourceManager.GetString("Page_Home_Auto_Install__NORTHSTARISNOTINSTALLEDANDAUTOINSTALLFAILED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to    Is not Valid.
        /// </summary>
        public static string Page_Home_Browse_Titanfall_Button_Click_IsNotValid {
            get {
                return ResourceManager.GetString("Page_Home_Browse_Titanfall_Button_Click_IsNotValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to   is Valid and has been Set.
        /// </summary>
        public static string Page_Home_Browse_Titanfall_Button_Click_IsValidAndHasBeenSet {
            get {
                return ResourceManager.GetString("Page_Home_Browse_Titanfall_Button_Click_IsValidAndHasBeenSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Location - &apos; .
        /// </summary>
        public static string Page_Home_Browse_Titanfall_Button_Click_TheLocation {
            get {
                return ResourceManager.GetString("Page_Home_Browse_Titanfall_Button_Click_TheLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current Titanfall 2 Path.
        /// </summary>
        public static string Page_Home_CurrentTitanfall2Path {
            get {
                return ResourceManager.GetString("Page_Home_CurrentTitanfall2Path", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Custom Modding And Server Framework.
        /// </summary>
        public static string Page_Home_CustomModdingAndServerFramework {
            get {
                return ResourceManager.GetString("Page_Home_CustomModdingAndServerFramework", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Indicates if Origin is running (Click To launch if inactive).
        /// </summary>
        public static string Page_Home_IndicatesIfOriginIsRunningClickToLaunchIfInactive {
            get {
                return ResourceManager.GetString("Page_Home_IndicatesIfOriginIsRunningClickToLaunchIfInactive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Install Northstar.
        /// </summary>
        public static string Page_Home_INIT_InstallNorthstar {
            get {
                return ResourceManager.GetString("Page_Home_INIT_InstallNorthstar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Install Path, Please manually locate the correct folder!.
        /// </summary>
        public static string Page_Home_INIT_InvalidInstallPathPleaseManuallyLocateTheCorrectFolder {
            get {
                return ResourceManager.GetString("Page_Home_INIT_InvalidInstallPathPleaseManuallyLocateTheCorrectFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NORTHSTAR AUTO INSTALL WILL NOW BEGIN, PLEASE WAIT ABOUT 30 SECONDS!.
        /// </summary>
        public static string Page_Home_INIT_NORTHSTARAUTOINSTALLWILLNOWBEGINPLEASEWAITABOUT30SECONDS {
            get {
                return ResourceManager.GetString("Page_Home_INIT_NORTHSTARAUTOINSTALLWILLNOWBEGINPLEASEWAITABOUT30SECONDS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update Northstar.
        /// </summary>
        public static string Page_Home_INIT_UpdateNorthstar {
            get {
                return ResourceManager.GetString("Page_Home_INIT_UpdateNorthstar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sequence contains no elements.
        /// </summary>
        public static string Page_Home_Install_NS_METHOD_SequenceContainsNoElements {
            get {
                return ResourceManager.GetString("Page_Home_Install_NS_METHOD_SequenceContainsNoElements", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to launch +Northstar&quot; .
        /// </summary>
        public static string Page_Home_LaunchNorthstar {
            get {
                return ResourceManager.GetString("Page_Home_LaunchNorthstar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Launch Titanfall 2 Northstar.
        /// </summary>
        public static string Page_Home_LaunchTitanfall2Northstar {
            get {
                return ResourceManager.GetString("Page_Home_LaunchTitanfall2Northstar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Locate Titanfall 2 Install.
        /// </summary>
        public static string Page_Home_LocateTitanfall2Install {
            get {
                return ResourceManager.GetString("Page_Home_LocateTitanfall2Install", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manually Change the Titanfall 2 Install Directory.
        /// </summary>
        public static string Page_Home_ManuallyChangeTheTitanfall2InstallDirectory {
            get {
                return ResourceManager.GetString("Page_Home_ManuallyChangeTheTitanfall2InstallDirectory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Master Server.
        /// </summary>
        public static string Page_Home_MasterServer {
            get {
                return ResourceManager.GetString("Page_Home_MasterServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Northstar Installation .
        /// </summary>
        public static string Page_Home_NorthstarInstallation {
            get {
                return ResourceManager.GetString("Page_Home_NorthstarInstallation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open Titanfall 2 Folder.
        /// </summary>
        public static string Page_Home_OpenTitanfall2Folder {
            get {
                return ResourceManager.GetString("Page_Home_OpenTitanfall2Folder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  The Origin Client Is already Running!.
        /// </summary>
        public static string Page_Home_Origin_Client_Card_Click_TheOriginClientIsAlreadyRunning {
            get {
                return ResourceManager.GetString("Page_Home_Origin_Client_Card_Click_TheOriginClientIsAlreadyRunning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Origin Client Running.
        /// </summary>
        public static string Page_Home_OriginClientRunning {
            get {
                return ResourceManager.GetString("Page_Home_OriginClientRunning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Could not Find EA Origin Install, Please Start Manually, Or Repair your installation!.
        /// </summary>
        public static string Page_Home_Run_Origin_CouldNotFindEAOriginInstallPleaseStartManuallyOrRepairYourInstallation {
            get {
                return ResourceManager.GetString("Page_Home_Run_Origin_CouldNotFindEAOriginInstallPleaseStartManuallyOrRepairYourIn" +
                        "stallation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shows the ping+latency over time.
        /// </summary>
        public static string Page_Home_ShowsThePingLatencyOverTime {
            get {
                return ResourceManager.GetString("Page_Home_ShowsThePingLatencyOverTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Master Server Checked And Timed Out too much. Turning off Master Server Checks.
        /// </summary>
        public static string Page_Home_timer_Tick_MasterServerCheckedAndTimedOutTooMuchTurningOffMasterServerChecks {
            get {
                return ResourceManager.GetString("Page_Home_timer_Tick_MasterServerCheckedAndTimedOutTooMuchTurningOffMasterServerC" +
                        "hecks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Toggle Checking.
        /// </summary>
        public static string Page_Home_ToggleChecking {
            get {
                return ResourceManager.GetString("Page_Home_ToggleChecking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to is not a zip!.
        /// </summary>
        public static string Page_Home_Unpack_To_Location_IsNotAZip {
            get {
                return ResourceManager.GetString("Page_Home_Unpack_To_Location_IsNotAZip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The File - .
        /// </summary>
        public static string Page_Home_Unpack_To_Location_TheFile {
            get {
                return ResourceManager.GetString("Page_Home_Unpack_To_Location_TheFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Was not Found!.
        /// </summary>
        public static string Page_Home_Unpack_To_Location_WasNotFound {
            get {
                return ResourceManager.GetString("Page_Home_Unpack_To_Location_WasNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update +Northstar.
        /// </summary>
        public static string Page_Home_UpdateNorthstar {
            get {
                return ResourceManager.GetString("Page_Home_UpdateNorthstar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome To.
        /// </summary>
        public static string Page_Home_WelcomeTo {
            get {
                return ResourceManager.GetString("Page_Home_WelcomeTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  and Manually repair the mod - .
        /// </summary>
        public static string Page_Mods_Call_Mods_From_Folder_AndManuallyRepairTheMod {
            get {
                return ResourceManager.GetString("Page_Mods_Call_Mods_From_Folder_AndManuallyRepairTheMod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mod Count: .
        /// </summary>
        public static string Page_Mods_Call_Mods_From_Folder_ModCount {
            get {
                return ResourceManager.GetString("Page_Mods_Call_Mods_From_Folder_ModCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Open your Folder at - .
        /// </summary>
        public static string Page_Mods_Call_Mods_From_Folder_PleaseOpenYourFolderAt {
            get {
                return ResourceManager.GetString("Page_Mods_Call_Mods_From_Folder_PleaseOpenYourFolderAt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is an Issue Detected with your Mod!.
        /// </summary>
        public static string Page_Mods_Call_Mods_From_Folder_ThereIsAnIssueDetectedWithYourMod {
            get {
                return ResourceManager.GetString("Page_Mods_Call_Mods_From_Folder_ThereIsAnIssueDetectedWithYourMod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filter.
        /// </summary>
        public static string Page_Mods_Filter {
            get {
                return ResourceManager.GetString("Page_Mods_Filter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Listed Here are the Mods that are Currently Installed..
        /// </summary>
        public static string Page_Mods_ListedHereAreTheModsThatAreCurrentlyInstalled {
            get {
                return ResourceManager.GetString("Page_Mods_ListedHereAreTheModsThatAreCurrentlyInstalled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MODS.
        /// </summary>
        public static string Page_Mods_MODS {
            get {
                return ResourceManager.GetString("Page_Mods_MODS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RightClick for Context Menu.
        /// </summary>
        public static string Page_Mods_RightClickForContextMenu {
            get {
                return ResourceManager.GetString("Page_Mods_RightClickForContextMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configure, Import and Export Dedicated Server and Client Settings.
        /// </summary>
        public static string Page_Server_ConfigureImportAndExportDedicatedServerAndClientSettings {
            get {
                return ResourceManager.GetString("Page_Server_ConfigureImportAndExportDedicatedServerAndClientSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export Server Config.
        /// </summary>
        public static string Page_Server_ExportServerConfig {
            get {
                return ResourceManager.GetString("Page_Server_ExportServerConfig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import Server Config.
        /// </summary>
        public static string Page_Server_ImportServerConfig {
            get {
                return ResourceManager.GetString("Page_Server_ImportServerConfig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could Not Find Northstar.exe!.
        /// </summary>
        public static string Page_Server_Launch_Northstar_Advanced_Click_CouldNotFindNorthstarExe {
            get {
                return ResourceManager.GetString("Page_Server_Launch_Northstar_Advanced_Click_CouldNotFindNorthstarExe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could Not Find Dedicated bat!.
        /// </summary>
        public static string Page_Server_Launch_Northstar_Dedicated_Click_CouldNotFindDedicatedBat {
            get {
                return ResourceManager.GetString("Page_Server_Launch_Northstar_Dedicated_Click_CouldNotFindDedicatedBat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Launch Northstar Client.
        /// </summary>
        public static string Page_Server_LaunchNorthstarClient {
            get {
                return ResourceManager.GetString("Page_Server_LaunchNorthstarClient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Launch Northstar Dedicated Client.
        /// </summary>
        public static string Page_Server_LaunchNorthstarDedicatedClient {
            get {
                return ResourceManager.GetString("Page_Server_LaunchNorthstarDedicatedClient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Launch Northstar Dedicated Server.
        /// </summary>
        public static string Page_Server_LaunchNorthstarDedicatedServer {
            get {
                return ResourceManager.GetString("Page_Server_LaunchNorthstarDedicatedServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reload Arguments.
        /// </summary>
        public static string Page_Server_Load_Files__ReloadArguments {
            get {
                return ResourceManager.GetString("Page_Server_Load_Files__ReloadArguments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load Files.
        /// </summary>
        public static string Page_Server_LoadFiles {
            get {
                return ResourceManager.GetString("Page_Server_LoadFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auto Save failed.
        /// </summary>
        public static string Page_Server_OnKeyDownHandler_Dedi_Arg_AutoSaveFailed {
            get {
                return ResourceManager.GetString("Page_Server_OnKeyDownHandler_Dedi_Arg_AutoSaveFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saved.
        /// </summary>
        public static string Page_Server_OnKeyDownHandler_Dedi_Arg_Saved {
            get {
                return ResourceManager.GetString("Page_Server_OnKeyDownHandler_Dedi_Arg_Saved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Cannot Set The path.
        /// </summary>
        public static string Page_Server_Read_Convar_args_CannotSetThePath {
            get {
                return ResourceManager.GetString("Page_Server_Read_Convar_args_CannotSetThePath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SERVER.
        /// </summary>
        public static string Page_Server_SERVER {
            get {
                return ResourceManager.GetString("Page_Server_SERVER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Startup Arguments Northstar Client.
        /// </summary>
        public static string Page_Server_StartupArgumentsNorthstarClient {
            get {
                return ResourceManager.GetString("Page_Server_StartupArgumentsNorthstarClient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Startup Arguments Northstar Dedicated Client.
        /// </summary>
        public static string Page_Server_StartupArgumentsNorthstarDedicatedClient {
            get {
                return ResourceManager.GetString("Page_Server_StartupArgumentsNorthstarDedicatedClient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot Read Input.
        /// </summary>
        public static string Page_Server_Validate_Combo_Box_CannotReadInput {
            get {
                return ResourceManager.GetString("Page_Server_Validate_Combo_Box_CannotReadInput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fine Tune And Configure VTOL Here.
        /// </summary>
        public static string Page_Settings_FineTuneAndConfigureVTOLHere {
            get {
                return ResourceManager.GetString("Page_Settings_FineTuneAndConfigureVTOLHere", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SETTINGS.
        /// </summary>
        public static string Page_Settings_SETTINGS {
            get {
                return ResourceManager.GetString("Page_Settings_SETTINGS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Browse.
        /// </summary>
        public static string Page_Skins_Browse {
            get {
                return ResourceManager.GetString("Page_Skins_Browse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Compatible Skin Found at : .
        /// </summary>
        public static string Page_Skins_Browse_Click_CompatibleSkinFoundAt {
            get {
                return ResourceManager.GetString("Page_Skins_Browse_Click_CompatibleSkinFoundAt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to   is Not a Skin Zip!.
        /// </summary>
        public static string Page_Skins_Browse_Click_IsNotASkinZip {
            get {
                return ResourceManager.GetString("Page_Skins_Browse_Click_IsNotASkinZip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Compatible Skin(s) Found : .
        /// </summary>
        public static string Page_Skins_Drag_Drop_Area_Drop_CompatibleSkinSFound {
            get {
                return ResourceManager.GetString("Page_Skins_Drag_Drop_Area_Drop_CompatibleSkinSFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Drag to Install.
        /// </summary>
        public static string Page_Skins_Drag_Drop_Area_Drop_DragToInstall {
            get {
                return ResourceManager.GetString("Page_Skins_Drag_Drop_Area_Drop_DragToInstall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to   is Not a Skin Zip!.
        /// </summary>
        public static string Page_Skins_Drag_Drop_Area_Drop_IsNotASkinZip {
            get {
                return ResourceManager.GetString("Page_Skins_Drag_Drop_Area_Drop_IsNotASkinZip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  - has been Installed!.
        /// </summary>
        public static string Page_Skins_Install_Skin_From_Path_HasBeenInstalled {
            get {
                return ResourceManager.GetString("Page_Skins_Install_Skin_From_Path_HasBeenInstalled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Skin - .
        /// </summary>
        public static string Page_Skins_Install_Skin_From_Path_TheSkin {
            get {
                return ResourceManager.GetString("Page_Skins_Install_Skin_From_Path_TheSkin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Install DDS Foramtted Skins Here.
        /// </summary>
        public static string Page_Skins_InstallDDSForamttedSkinsHere {
            get {
                return ResourceManager.GetString("Page_Skins_InstallDDSForamttedSkinsHere", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Install Skin.
        /// </summary>
        public static string Page_Skins_InstallSkin {
            get {
                return ResourceManager.GetString("Page_Skins_InstallSkin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Making Your Own Skin.
        /// </summary>
        public static string Page_Skins_MakingYourOwnSkin {
            get {
                return ResourceManager.GetString("Page_Skins_MakingYourOwnSkin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opening the Following URL - .
        /// </summary>
        public static string Page_Skins_OPEN_WEBPAGE_OpeningTheFollowingURL {
            get {
                return ResourceManager.GetString("Page_Skins_OPEN_WEBPAGE_OpeningTheFollowingURL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open a Guide Page.
        /// </summary>
        public static string Page_Skins_OpenAGuidePage {
            get {
                return ResourceManager.GetString("Page_Skins_OpenAGuidePage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open the FAQ Page.
        /// </summary>
        public static string Page_Skins_OpenTheFAQPage {
            get {
                return ResourceManager.GetString("Page_Skins_OpenTheFAQPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SKINS.
        /// </summary>
        public static string Page_Skins_SKINS {
            get {
                return ResourceManager.GetString("Page_Skins_SKINS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to These are the Collection of Mods Hosted On the ThunderStore Mod platform..
        /// </summary>
        public static string Page_Thunderstore_TheseAreTheCollectionOfModsHostedOnTheThunderStoreModPlatform {
            get {
                return ResourceManager.GetString("Page_Thunderstore_TheseAreTheCollectionOfModsHostedOnTheThunderStoreModPlatform", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to THUNDERSTORE.
        /// </summary>
        public static string Page_Thunderstore_THUNDERSTORE {
            get {
                return ResourceManager.GetString("Page_Thunderstore_THUNDERSTORE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  has been Downloaded and Installed.
        /// </summary>
        public static string Page_Thunderstore_Unpack_To_Location_Custom_HasBeenDownloadedAndInstalled {
            get {
                return ResourceManager.GetString("Page_Thunderstore_Unpack_To_Location_Custom_HasBeenDownloadedAndInstalled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Author Name.
        /// </summary>
        public static string Page_Tools_AuthorName {
            get {
                return ResourceManager.GetString("Page_Tools_AuthorName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose Your Item.
        /// </summary>
        public static string Page_Tools_ChooseYourItem {
            get {
                return ResourceManager.GetString("Page_Tools_ChooseYourItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Content.
        /// </summary>
        public static string Page_Tools_Content {
            get {
                return ResourceManager.GetString("Page_Tools_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Convert Skin.
        /// </summary>
        public static string Page_Tools_ConvertSkin {
            get {
                return ResourceManager.GetString("Page_Tools_ConvertSkin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  One of the Manifest Inputs are Empty.
        /// </summary>
        public static string Page_Tools_create_Manifest_OneOfTheManifestInputsAreEmpty {
            get {
                return ResourceManager.GetString("Page_Tools_create_Manifest_OneOfTheManifestInputsAreEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Skin.
        /// </summary>
        public static string Page_Tools_CreateSkin {
            get {
                return ResourceManager.GetString("Page_Tools_CreateSkin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dependencies.
        /// </summary>
        public static string Page_Tools_Dependencies {
            get {
                return ResourceManager.GetString("Page_Tools_Dependencies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string Page_Tools_Description {
            get {
                return ResourceManager.GetString("Page_Tools_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Drag and Drop or Click to populate the Maps.
        /// </summary>
        public static string Page_Tools_DragAndDropOrClickToPopulateTheMaps {
            get {
                return ResourceManager.GetString("Page_Tools_DragAndDropOrClickToPopulateTheMaps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Icon.
        /// </summary>
        public static string Page_Tools_Icon {
            get {
                return ResourceManager.GetString("Page_Tools_Icon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Image Size!. Must be 256x256.
        /// </summary>
        public static string Page_Tools_Icon_Image_MouseDown_InvalidImageSizeMustBe256x256 {
            get {
                return ResourceManager.GetString("Page_Tools_Icon_Image_MouseDown_InvalidImageSizeMustBe256x256", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not A Valid PNG Image.
        /// </summary>
        public static string Page_Tools_Icon_Image_MouseDown_NotAValidPNGImage {
            get {
                return ResourceManager.GetString("Page_Tools_Icon_Image_MouseDown_NotAValidPNGImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to That was not a proper PNG.
        /// </summary>
        public static string Page_Tools_Icon_Image_MouseDown_ThatWasNotAProperPNG {
            get {
                return ResourceManager.GetString("Page_Tools_Icon_Image_MouseDown_ThatWasNotAProperPNG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Valid Image Found at - .
        /// </summary>
        public static string Page_Tools_Icon_Image_MouseDown_ValidImageFoundAt {
            get {
                return ResourceManager.GetString("Page_Tools_Icon_Image_MouseDown_ValidImageFoundAt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Image Size!. Must be smaller than 2048 x 2048.
        /// </summary>
        public static string Page_Tools_Image_Icon_Drop_InvalidImageSizeMustBeSmallerThan2048X2048 {
            get {
                return ResourceManager.GetString("Page_Tools_Image_Icon_Drop_InvalidImageSizeMustBeSmallerThan2048X2048", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item.
        /// </summary>
        public static string Page_Tools_Item {
            get {
                return ResourceManager.GetString("Page_Tools_Item", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Locate_Repak_Exe.
        /// </summary>
        public static string Page_Tools_Locate_Repak_Exe {
            get {
                return ResourceManager.GetString("Page_Tools_Locate_Repak_Exe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Zip Found.
        /// </summary>
        public static string Page_Tools_Locate_Zip_Click_InvalidZipFound {
            get {
                return ResourceManager.GetString("Page_Tools_Locate_Zip_Click_InvalidZipFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Valid Zip Found.
        /// </summary>
        public static string Page_Tools_Locate_Zip_Click_ValidZipFound {
            get {
                return ResourceManager.GetString("Page_Tools_Locate_Zip_Click_ValidZipFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Locate Repak Exe.
        /// </summary>
        public static string Page_Tools_LocateRepakExe {
            get {
                return ResourceManager.GetString("Page_Tools_LocateRepakExe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Locate Skin Content.
        /// </summary>
        public static string Page_Tools_LocateSkinContent {
            get {
                return ResourceManager.GetString("Page_Tools_LocateSkinContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Locate the Mod Zip manually.
        /// </summary>
        public static string Page_Tools_LocateTheModZipManually {
            get {
                return ResourceManager.GetString("Page_Tools_LocateTheModZipManually", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string Page_Tools_Name {
            get {
                return ResourceManager.GetString("Page_Tools_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not An Output Directory.
        /// </summary>
        public static string Page_Tools_Output_Button_Click_NotAnOutputDirectory {
            get {
                return ResourceManager.GetString("Page_Tools_Output_Button_Click_NotAnOutputDirectory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Output As a Thunderstore Mod.
        /// </summary>
        public static string Page_Tools_OutputAsAThunderstoreMod {
            get {
                return ResourceManager.GetString("Page_Tools_OutputAsAThunderstoreMod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Output Directory.
        /// </summary>
        public static string Page_Tools_OutputDirectory {
            get {
                return ResourceManager.GetString("Page_Tools_OutputDirectory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Package as a DDS Skin?.
        /// </summary>
        public static string Page_Tools_PackageAsADDSSkin {
            get {
                return ResourceManager.GetString("Page_Tools_PackageAsADDSSkin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generated The Skin Successfully!.
        /// </summary>
        public static string Page_Tools_ProcessSkin_GeneratedTheSkinSuccessfully {
            get {
                return ResourceManager.GetString("Page_Tools_ProcessSkin_GeneratedTheSkinSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item Not Set!.
        /// </summary>
        public static string Page_Tools_ProcessSkin_ItemNotSet {
            get {
                return ResourceManager.GetString("Page_Tools_ProcessSkin_ItemNotSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maps Are not Set!.
        /// </summary>
        public static string Page_Tools_ProcessSkin_MapsAreNotSet {
            get {
                return ResourceManager.GetString("Page_Tools_ProcessSkin_MapsAreNotSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Output path is not set!.
        /// </summary>
        public static string Page_Tools_ProcessSkin_OutputPathIsNotSet {
            get {
                return ResourceManager.GetString("Page_Tools_ProcessSkin_OutputPathIsNotSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skin Name Not Set!.
        /// </summary>
        public static string Page_Tools_ProcessSkin_SkinNameNotSet {
            get {
                return ResourceManager.GetString("Page_Tools_ProcessSkin_SkinNameNotSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Valid Mod ICON Found.
        /// </summary>
        public static string Page_Tools_Save_Mod_Click_NoValidModICONFound {
            get {
                return ResourceManager.GetString("Page_Tools_Save_Mod_Click_NoValidModICONFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Valid Output Path Found.
        /// </summary>
        public static string Page_Tools_Save_Mod_Click_NoValidOutputPathFound {
            get {
                return ResourceManager.GetString("Page_Tools_Save_Mod_Click_NoValidOutputPathFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Valid Zip file to pack was found.
        /// </summary>
        public static string Page_Tools_Save_Mod_Click_NoValidZipFileToPackWasFound {
            get {
                return ResourceManager.GetString("Page_Tools_Save_Mod_Click_NoValidZipFileToPackWasFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Successfully Packed all items to -.
        /// </summary>
        public static string Page_Tools_Save_Mod_Click_SuccessfullyPackedAllItemsTo {
            get {
                return ResourceManager.GetString("Page_Tools_Save_Mod_Click_SuccessfullyPackedAllItemsTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skin Name.
        /// </summary>
        public static string Page_Tools_SkinName {
            get {
                return ResourceManager.GetString("Page_Tools_SkinName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Test Readme Text.
        /// </summary>
        public static string Page_Tools_TestReadmeText {
            get {
                return ResourceManager.GetString("Page_Tools_TestReadmeText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TOOLS.
        /// </summary>
        public static string Page_Tools_TOOLS {
            get {
                return ResourceManager.GetString("Page_Tools_TOOLS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tools For Ease of Development on the Northstar Client.
        /// </summary>
        public static string Page_Tools_ToolsForEaseOfDevelopmentOnTheNorthstarClient {
            get {
                return ResourceManager.GetString("Page_Tools_ToolsForEaseOfDevelopmentOnTheNorthstarClient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version.
        /// </summary>
        public static string Page_Tools_Version {
            get {
                return ResourceManager.GetString("Page_Tools_Version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version Number.
        /// </summary>
        public static string Page_Tools_VersionNumber {
            get {
                return ResourceManager.GetString("Page_Tools_VersionNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Webpage.
        /// </summary>
        public static string Page_Tools_Webpage {
            get {
                return ResourceManager.GetString("Page_Tools_Webpage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Release Not Found!.
        /// </summary>
        public static string Parse_Release_ReleaseNotFound {
            get {
                return ResourceManager.GetString("Parse_Release_ReleaseNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Wait as VTOL restarts!.
        /// </summary>
        public static string PleaseWaitAsVTOLRestarts {
            get {
                return ResourceManager.GetString("PleaseWaitAsVTOLRestarts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Release Donwload URL!.
        /// </summary>
        public static string Read_Latest_Release_InvalidReleaseDonwloadURL {
            get {
                return ResourceManager.GetString("Read_Latest_Release_InvalidReleaseDonwloadURL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Installation Complete!.
        /// </summary>
        public static string Unpack_To_Location_InstallationComplete {
            get {
                return ResourceManager.GetString("Unpack_To_Location_InstallationComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  The File - .
        /// </summary>
        public static string Unpack_To_Location_TheFile {
            get {
                return ResourceManager.GetString("Unpack_To_Location_TheFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Was not Found!.
        /// </summary>
        public static string Unpack_To_Location_WasNotFound {
            get {
                return ResourceManager.GetString("Unpack_To_Location_WasNotFound", resourceCulture);
            }
        }
    }
}
